# Computational methods in Physics
## Week 5
#### Prof. Michael Wood-Vasey
##### [based on materials from Prof. Brian D'Urso]
##### University of Pittsburgh, Department of Physics and Astronomy

## Linear algebra

## Overview
This week's topics:
* Numerical Differentiation
  + Forward, Central, Extrapolated Difference Methods
  + Second derivatives
* Writing and reading arrays to/from files.
* Linear algebra and matrix methods.

## Numerical Differentiation

### Numerical Differentiation
We know how to integrate numerically, how about differentiating?

* Numerical derivatives are even easier than integrals!
* Go back to definition of derivative:
$$
f^\prime (x) = \frac{d}{dx}f(x) = \lim_{\epsilon\to 0} \frac{f(x+\epsilon)-f(x)}{\epsilon}
$$
* As with integration, use finite $\epsilon$ instead of $\epsilon\to 0$.
* This will give us another piece of the puzzle for solving differential equations (ODEs and PDEs) numerically.

### Forward Difference Method

* Start with the forward difference operator $D_f\left[f(x), h\right]$:
$$
f^\prime(x) \simeq D_f\left[f(x), h\right] = \frac{f(x+h)-f(x)}{h}
$$
* Compare to the Taylor expansion of $f(x+h)$:
$$
f(x+h) = f(x) + h f^\prime(x) + \frac{h^2}{2} f^{\prime\prime}(x) + \cdots
$$
* By comparison, we see:
$$
D_f\left[f(x), h\right] = f^\prime(x) + \frac{h}{2} f^{\prime\prime}(x) + \cdots
\approx f^\prime(x) + \mathcal{O}(h)
$$
* So, the error scales as $h$.

### Forward Difference Example

* Consider the function: $f(x) = a + b x^2$
* The exact derivative is $f^\prime(x) = 2 b x$
* Applying the Forward Difference Approximation gives:
$$
f^\prime(x) \simeq \frac{f(x+h)-f(x)}{h} = 2 b x + b h
$$
* As expected, error $\propto h \Rightarrow$ need very small $h$.

### Improvement: Central Difference Method

* Start with the same $h$, but make the difference symmetrical:
$$
f^\prime(x) \simeq D_{cd}\left[f(x), h\right] = \frac{f(x+h/2)-f(x-h/2)}{h}
$$
* Again, by comparison with the Taylor series at $f(x \pm h/2)$:
$$
D_{cd}\left[f(x), h\right] = f^\prime(x) + \frac{1}{24} h^2 f^{(3)}(x) + \cdots
\approx f^\prime(x) + \mathcal{O}(h^2)
$$
* All even derivatives cancel.
* Now the error $\propto h^2$ (one order better than forward difference).
* Exact for $f(x) = a + b x^2$.
* Better rule $\Rightarrow$ can use larger $h$.

### Extrapolated Difference Method

* Consider the error in the central difference method:
$$
D_{cd}[f(x), h] \simeq f^\prime (x) + \frac{1}{24}h^2 f^{\prime\prime\prime}(x) + \mathcal{O}(h^4)
$$
* Compare to:
$$
D_{cd}[f(x), h/2] \simeq f^\prime (x) + \frac{1}{96}h^2 f^{\prime\prime\prime}(x) + \mathcal{O}(h^4)
$$
* Cancel the quadratic term using the difference between the two $\Rightarrow$ *Extrapolated Difference Method*:
$$
D_{ed}[f(x), h] = \frac{4 D_{cd}[f(x), h/2] - D_{cd}[f(x), h]}{3}
\approx f^\prime (x) + \frac{h^4 f^{(5)}(x)}{4\times 16 \times 120} + \cdots
$$

### Second Derivatives

* Start with the central difference method:
$$
f^\prime(x) \simeq D_{cd}\left[f(x), h\right] = \frac{f(x+h/2)-f(x-h/2)}{h}
$$
* Apply central difference method twice:
$$f^{\prime\prime}(x) \approx D_{cd}[f^\prime (x), h] \approx D_{cd}\left[D_{cd}[f(x), h], h\right]  $$
$$                    \approx \frac{f^\prime(x+h/2)-f^\prime(x-h/2)}{h}$$  
$$                    \approx \frac{[f(x+h)-f(x)]-[f(x)-f(x-h)]}{h^2}  $$
$$                    \approx \frac{f(x+h)-2 f(x)+f(x-h)}{h^2}  $$


### Matrices

#### Creating Arrays in Numpy
* Creating arrays:
  * Online documentation:  
    http://docs.scipy.org/doc/numpy/reference/routines.array-creation.html
* Writing to a file:
  * Online documentation:  
    http://docs.scipy.org/doc/numpy/reference/generated/numpy.savetxt.html
  * Python help:
  `help(numpy.savetxt)`
* Loading from a file:
  * Online documentation:  
  http://docs.scipy.org/doc/numpy/reference/generated/numpy.loadtxt.html
  * Python help:  
  `help(numpy.loadtxt)`
* There are other fileIO functions:
  e.g. `numpy.load` and `numpy.save`.
* and other formats (e.g., `hdf`) and frameworks (e.g., `astropy.Tables`).

#### Examples: Arrays and Files
* Setup:

In [1]:
import numpy as np
A = np.array([[0.0, 2.5, 3.2],
              [1.0, 5.6, 8.9],
              [2.0, 7.1, 3.7],
              [3.0, 4.2, 9.3]])

* Save $\mathbf{A}$ to a file:

In [2]:
np.savetxt('A_test.csv', A,
           delimiter=',', fmt='%g')

* Load the array back from the file:

In [3]:
B = np.loadtxt('A_test.csv',
               delimiter=',')

In [4]:
print(B)

[[ 0.   2.5  3.2]
 [ 1.   5.6  8.9]
 [ 2.   7.1  3.7]
 [ 3.   4.2  9.3]]


* Let's take a moment to look at the file. [...]  

In [5]:
foo = {"PHYS" : "Physics", "ASTRON" : "Astronomy"}

In [6]:
print(foo['PHYS'])

Physics


In [7]:
for key, value in foo.items():
    print(key, value)

PHYS Physics
ASTRON Astronomy


### Linear Algebra

#### Linear Algebra Problems
* The basic linear algebra problem is a set of $m$ simultaneous linear equations with $n$ unknowns:
\begin{equation*}
\begin{matrix}
 \alpha_{0,0}x_0   &+& \alpha_{0,1}x_1   &+& \cdots &+& \alpha_{0,n-1}x_{n-1}  &=& b_0 \\
 \alpha_{1,0}x_0   &+& \alpha_{1,1}x_1   &+& \cdots &+& \alpha_{1,n-1}x_{n-1}  &=& b_1 \\
 \vdots            &+& \vdots            &+& \ddots &+& \vdots                 &=& \vdots \\
 \alpha_{m-1,0}x_0 &+& \alpha_{m-1,1}x_1 &+& \cdots &+& \alpha_{m-1,n-1}x_{n-1}&=& b_{m-1} \\
\end{matrix}
\end{equation*}
* Typically, we know $\alpha_{i,j}$ and $b_i$, and want to find $x_j$.
* If $m>n$, the system is overdetermined.
* If $m<n$, the system is underdetermined.
* We will look primarily at the case $n=m$.

#### Matrix Representation
* Computers are better able to handle equations as matrix equations.
* Matrix representation:

\begin{equation*}
\begin{pmatrix}
\alpha_{0,0}   & \alpha_{0,1}   & \cdots & \alpha_{0,n-1}   \\
\alpha_{1,0}   & \alpha_{1,1}   & \cdots & \alpha_{1,n-1}   \\
\vdots         & \vdots         & \ddots & \vdots           \\
\alpha_{m-1,0} & \alpha_{m-1,1} & \cdots & \alpha_{m-1,n-1} \\
\end{pmatrix}
\begin{pmatrix}
x_0 \\
x_1 \\
\vdots \\
x_{n-1} \\
\end{pmatrix}
=
\begin{pmatrix}
b_0 \\
b_1 \\
\vdots \\
b_{m-1} \\
\end{pmatrix}
\end{equation*}

* We can write this set of equations in a compact form, writing the matrix as $\mathbf{A}$:

\begin{equation*}
\mathbf{A}\vec{x} = \vec{b}
\end{equation*}

* Here $\mathbf{A}$ is a square matrix.

#### Classes of Matrix Problems
$\mathbf{A}\vec{x}=\vec{b}$
* $\mathbf{A}$ is a known $N \times N$ matrix.
* $\vec{x}$ is an unknown vector of length $N$.
* $\vec{b}$ is a known vector of length $N$.
* Solve with Gaussian elimination
 or lower-upper (LU) decomposition.
* Slower: solve by finding $\mathbf{A}^{-1}$, then $\vec{x}=\mathbf{A}^{-1}\vec{b}$.
$\mathbf{A}\vec{x}=\lambda\vec{x}$
* Eigenvector $\vec{x}$ is an unknown vector of length $N$.
* Eigenvalue $\lambda$ is an unknown parameter.
* $\mathbf{A}^{-1}$ doesn't help! Need specialized solver.
* Can shown that $\textrm{det}[\mathbf{A}-\lambda\mathbf{I}] = 0$ for eigenvalues $\lambda$.

#### Linear Algebra Routines
* We *will* solve linear algebra problems with "canned" routines.
* Eigensystems, matrix multiplication, inverses, determinants, etc.
* Many tested and optimized packages available:
NETLIB, LAPACK, SLATEC, BLAS, \ldots
* Writing custom solvers "from scratch" is not usually worthwhile for these.
* NumPy and SciPy wrap some of these.
* We will primarily use the NumPy routines in `numpy.linalg`.

#### Linear Algebra in Numpy
Common linear algebra functions available in `numpy`:
* Online documentation:
  http://docs.scipy.org/doc/numpy/reference/routines.linalg.html
* Python help:
  `help(numpy.linalg)`

#### Examples: Solving Linear Systems
* Setup matrices:

In [8]:
import numpy as np
A = np.array([[ 1,  2,   3],
              [22, 32,  42],
              [55, 66, 100]])
b = np.array([1, 2, 3])

* Solve $\mathbf{A}\vec{x}=\vec{b}$:

In [9]:
x = np.linalg.solve(A, b)
print(x)

[-1.4057971  -0.1884058   0.92753623]


* Check accuracy of the solution by calculating $\mathbf{A}\vec{x}-\vec{b}$:

In [10]:
np.dot(A, x) - b

array([  0.00000000e+00,   2.66453526e-15,   3.10862447e-15])

* Less efficient direct solution, $\vec{x}=\mathbf{A}^{-1}\vec{b}$:

In [11]:
A_inverse = np.linalg.inv(A)

print(np.dot(A_inverse, A))
x = np.dot(A_inverse, b)


[[  1.00000000e+00  -4.30211422e-16  -8.88178420e-16]
 [  6.93889390e-16   1.00000000e+00  -1.77635684e-15]
 [ -8.88178420e-16  -4.44089210e-16   1.00000000e+00]]


In [12]:
print(x)

[-1.4057971  -0.1884058   0.92753623]
